name: Build
on:
  - push

jobs:
  simple-build:
    strategy:
      matrix:
        os: [macos, windows]
    runs-on: ${{matrix.os}}-latest
    steps:
    - uses: actions/checkout@v2
    - uses: m4c0/gha-simple-cmake@e3ac067bb0eb9eb5fbd71bfe8d3ab6d629b873db

  android:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        abi: [armeabi-v7a, arm64-v8a, x86, x86_64]
    steps:
    - uses: actions/checkout@v2
    - id: ndk
      run: echo "::set-output name=ANDROID_NDK::${ANDROID_SDK_ROOT}/ndk-bundle"
    - uses: m4c0/gha-simple-cmake@e3ac067bb0eb9eb5fbd71bfe8d3ab6d629b873db
      env:
        ndk: ${{ steps.ndk.outputs.ANDROID_NDK }}
      with:
        extra_configure_flags: >
          -DANDROID_ABI=${{ matrix.abi }} 
          -DANDROID_NATIVE_API_LEVEL=26 
          -DANDROID_TOOLCHAIN=clang 
          -DANDROID_NDK=${{ env.ndk }}
          -DCMAKE_TOOLCHAIN_FILE=${{ env.ndk }}/build/cmake/android.toolchain.cmake

  ios:
    runs-on: macosx-latest
    steps:
    - uses: actions/checkout@v2
    - uses: m4c0/gha-simple-cmake@e3ac067bb0eb9eb5fbd71bfe8d3ab6d629b873db
      with:
        extra_configure_flags: -GXcode -DCMAKE_SYSTEM_NAME=iOS -DCMAKE_OSX_DEPLOYMENT_TARGET=13.0 -DCMAKE_OSX_ARCHITECTURES=x86_64
        extra_build_flags: -- -sdk iphonesimulator

